"""
Yelp Fusion API code sample.

This program demonstrates the capability of the Yelp Fusion API
by using the Search API to query for businesses by a search term and location,
and the Business API to query additional information about the top result
from the search query.

Please refer to https://docs.developer.yelp.com/docs/get-started for the API
documentation.

This program requires the Python requests library, which you can install via:
`pip install -r requirements.txt`.

Sample usage of the program:
`python sample.py --term="bars" --location="San Francisco, CA"`
"""
from __future__ import print_function

import argparse
import json
import pprint
import requests
import sys
import urllib
import csv
import json


# This client code can run on Python 2.x or 3.x.  Your imports can be
# simpler if you only need one of those.
try:
    # For Python 3.0 and later
    from urllib.error import HTTPError
    from urllib.parse import quote
    from urllib.parse import urlencode
except ImportError:
    # Fall back to Python 2's urllib2 and urllib
    # from urllib2 import HTTPError
    from urllib import quote
    from urllib import urlencode


# Yelp Fusion no longer uses OAuth as of December 7, 2017.
# You no longer need to provide Client ID to fetch Data
# It now uses private keys to authenticate requests (API Key)
# You can find it on
# https://www.yelp.com/developers/v3/manage_app
API_KEY= "-3m06UC4k-vFlR7ZXosa6kUMtoH5FPh-hltHHfLgGBAIllqKZHKjyMk-Spk5bWmum0yPo3rfLwja2UQQqQEBchRPi94JbqrJp2K7e1qw-Pi7yFRVYSQ2TG92dWEmZ3Yx"


# API constants, you shouldn't have to change these.
API_HOST = 'https://api.yelp.com'
SEARCH_PATH = '/v3/businesses/search'
BUSINESS_PATH = '/v3/businesses/'  # Business ID will come after slash.


# Defaults for our simple example.
DEFAULT_TERM = 'Active Life'
DEFAULT_LOCATION = 'New York'
SEARCH_LIMIT = 30

categories = ["Active Life", "Arts & Entertainment", "Beauty & Spas", "Event Planning & Services", "Food", "Hotels & Travel"]
businesses = None
better_categories_list = {
    'Active Life' : """ATV Rentals/Tours (atvrentals, [AT, ES, DE, AR, NL, MX, PL, SE, FI, CL, CH, NO, BE, US])
Airsoft (airsoft, All)
Amateur Sports Teams (amateursportsteams, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Amusement Parks (amusementparks, All)
Aquariums (aquariums, All)
Archery (archery, All)
Axe Throwing (axethrowing, [GB, CA, US])
Badminton (badminton, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, PH, PT, SE, TR, TW, US])
Baseball Fields (baseballfields, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Basketball Courts (basketballcourts, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, FR, HK, IT, JP, MX, MY, NO, NZ, PH, PT, SG, TR, TW, US])
Bathing Area (bathing_area, [AT, DE, PT, SE, CZ, FI, CH, NO, DK, JP])
Batting Cages (battingcages, [TW, JP, SG, US])
Beach Equipment Rentals (beachequipmentrental, All)
Beach Volleyball (beachvolleyball, [AR, AT, AU, BR, CL, CZ, DE, DK, ES, FI, JP, MX, NO, PT, SE, SG])
Beaches (beaches, All)
Bicycle Paths (bicyclepaths, [AR, AU, BE, BR, CL, CZ, DK, ES, FI, GB, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG])
Bike Parking (bikeparking, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bike Rentals (bikerentals, All)
Boating (boating, All)
Bobsledding (bobsledding, All)
Bocce Ball (bocceball, All)
Bowling (bowling, All)
Bubble Soccer (bubblesoccer, All)
Bungee Jumping (bungeejumping, All)
Canyoneering (canyoneering, All)
Carousels (carousels, All)
Challenge Courses (challengecourses, [AT, DE, NZ, HK, PL, SE, FR, CH, DK, CZ, NO, SG, CA, US])
Climbing (climbing, All)
Cycling Classes (cyclingclasses, [AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IT, JP, MY, NL, NO, PH, PL, SE, SG, TR, TW, US])
Dart Arenas (dartarenas, [AT, DE, CH, PL, US])
Day Camps (daycamps, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Disc Golf (discgolf, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Diving (diving, All)
Free Diving (freediving, All)
Scuba Diving (scuba, All)
Escape Games (escapegames, All)
Experiences (experiences, [DE, NO, PT, DK, SE, CZ])
Fencing Clubs (fencing, All)
Fishing (fishing, All)
Fitness & Instruction (fitness, All)
Aerial Fitness (aerialfitness, All)
Barre Classes (barreclasses, [GB, IE, PT, NL, NZ, AU, FI, BE, DK, NO, CZ, CA, US])
Boot Camps (bootcamps, [ES, PT, NZ, PL, AU, SE, IT, NO, CZ, DK, US])
Boxing (boxing, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, TW, US])
Cardio Classes (cardioclasses, All)
Dance Studios (dancestudio, All)
EMS Training (emstraining, [AT, ES, DE, CH, SE])
Golf Lessons (golflessons, [AR, AU, BE, CL, CZ, DK, ES, FR, GB, IT, JP, MX, NL, NO, NZ, PL, PT, SE, US])
Gyms (gyms, All)
Circuit Training Gyms (circuittraininggyms, [US])
Interval Training Gyms (intervaltraininggyms, [US])
Martial Arts (martialarts, All)
Brazilian Jiu-jitsu (brazilianjiujitsu, All)
Chinese Martial Arts (chinesemartialarts, All)
Karate (karate, All)
Kickboxing (kickboxing, All)
Muay Thai (muaythai, All)
Taekwondo (taekwondo, All)
Meditation Centers (meditationcenters, All)
Pilates (pilates, All)
Qi Gong (qigong, All)
Self-defense Classes (selfdefenseclasses, All)
Swimming Lessons/Schools (swimminglessons, All)
Tai Chi (taichi, All)
Trainers (healthtrainers, All)
Yoga (yoga, All)
Flyboarding (flyboarding, All)
Gliding (gliding, [AT, DE, PT, PL, SE, CH, NO, CZ, FR])
Go Karts (gokarts, All)
Golf (golf, All)
Gun/Rifle Ranges (gun_ranges, [AR, AU, BR, CA, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Gymnastics (gymnastics, [BR, PT, NZ, MX, DK, NO, CZ, CA, US])
Handball (handball, [AR, AT, BE, BR, CH, CL, DK, ES, FI, FR, IT, JP, NL, NO, PL, SE])
Hang Gliding (hanggliding, [AR, AT, AU, BE, BR, CH, CL, ES, FR, IT, JP, MX, NO, NZ, PT, SE, US])
Hiking (hiking, All)
Horse Racing (horseracing, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, HK, JP, MX, NL, NO, PL, PT, SE, TR, TW, US])
Horseback Riding (horsebackriding, All)
Hot Air Balloons (hot_air_balloons, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, PH, PL, PT, SE, TR, TW, US])
Indoor Playcentre (indoor_playcenter, [AU, BE, CA, CZ, DE, DK, ES, FR, GB, IT, JP, NL, NO, NZ, PT, SE, US])
Jet Skis (jetskis, All)
Kids Activities (kids_activities, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Kiteboarding (kiteboarding, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Lakes (lakes, All)
Laser Tag (lasertag, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Lawn Bowling (lawn_bowling, [FI, PT, NO, NZ, AU, SE])
Mini Golf (mini_golf, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Mountain Biking (mountainbiking, All)
Nudist (nudist, [AT, IE, BR, ES, DE, NZ, AU, SE, CZ, DK, PT, FR, BE, US, GB, NL, PL, FI, CH, NO, CA])
Paddleboarding (paddleboarding, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, MX, NL, NO, NZ, PL, PT, SG, US])
Paintball (paintball, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Paragliding (paragliding, All)
Parasailing (parasailing, All)
Parks (parks, All)
Dog Parks (dog_parks, All)
Skate Parks (skate_parks, All)
Pickleball (pickleball, [AT, DE, CH, PL, US])
Playgrounds (playgrounds, All)
Public Plazas (publicplazas, [AR, AT, BR, CH, CL, CZ, DE, DK, ES, FI, FR, HK, IT, JP, MX, MY, NO, PH, PL, PT, SE, SG, TR, TW])
Races & Competitions (races, [AT, AU, BE, BR, CH, CZ, DE, DK, FR, GB, NL, NO, NZ, PL, SE, SG, US])
Racing Experience (racingexperience, [FR, SE, US])
Rafting/Kayaking (rafting, All)
Recreation Centers (recreation, All)
Rock Climbing (rock_climbing, All)
Sailing (sailing, All)
Scavenger Hunts (scavengerhunts, [US])
Scooter Rentals (scooterrentals, All)
Senior Centers (seniorcenters, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Skating Rinks (skatingrinks, All)
Skiing (skiing, [AR, AT, BE, CA, CH, CL, CZ, DE, DK, ES, FI, JP, NL, NO, NZ, PT, SE])
Skydiving (skydiving, All)
Sledding (sledding, [AT, DE, PT, NZ, TR, FI, IT, CH, NO, CZ, CA, US])
Snorkeling (snorkeling, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Soccer (football, All)
Sport Equipment Hire (sport_equipment_hire, [ES, PT, MX, AU, CL, DK, NO, CZ, AR])
Sports Clubs (sports_clubs, All)
Squash (squash, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, PH, PL, SE, TR, TW, US])
Summer Camps (summer_camps, All)
Surf Lifesaving (surflifesaving, [BR, ES, NZ, MX, AU, CL, PT, AR])
Surfing (surfing, [BR, ES, DE, NL, NZ, MX, SE, CL, FR, IT, DK, PT, AR, JP, US])
Swimming Pools (swimmingpools, All)
Tennis (tennis, All)
Trampoline Parks (trampoline, [AT, AU, BE, CA, CH, CZ, DE, DK, FI, FR, GB, IE, IT, NL, NO, PL, PT, SE, TR, US])
Tubing (tubing, [US])
Volleyball (volleyball, [AT, BR, DE, NZ, AU, SE, FI, FR, NO, SG, CZ, DK, JP])
Water Parks (waterparks, [BE, BR, CA, CZ, DK, ES, FR, IT, JP, MX, NL, NO, PH, PL, PT, SE, SG, TR, TW, US])
Wildlife Hunting Ranges (wildlifehunting, [US])
Ziplining (zipline, All)
Zoos (zoos, All)
Petting Zoos (pettingzoos, [AT, GB, ES, DE, NL, IT, CH, DK, NO, BE, US])
Zorbing (zorbing, [ES, PT, CZ, NZ, MX, US])""",

'Arts & Entertainment' : """Arcades (arcades, All)
Art Galleries (galleries, All)
Betting Centers (bettingcenters, [AR, AT, AU, BE, BR, CH, CL, CZ, DE, DK, ES, GB, HK, IE, IT, JP, MX, MY, NL, PH, PL, PT, SE, TR, TW])
Bingo Halls (bingo, [GB, IE, BR, ES, NZ, MX, AU, SE, FI, CL, IT, DK, NO, AR, US])
Botanical Gardens (gardens, All)
Cabaret (cabaret, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Casinos (casinos, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Castles (castles, [AT, GB, ES, DE, PT, SE, FI, FR, IT, CH, DK, CZ, NO, BE, JP])
Choirs (choirs, [AR, AT, AU, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NO, PH, PT, SE, TR, TW])
Cinema (movietheaters, All)
Drive-In Theater (driveintheater, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PT, SE, SG, TR, TW, US])
Outdoor Movies (outdoormovies, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SE, SG, TR, TW, US])
Country Clubs (countryclubs, [TW, BR, ES, HK, MX, CL, IT, SG, AR, JP, US])
Cultural Center (culturalcenter, [AR, AT, AU, BE, BR, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, SE, SG, TW, US])
Eatertainment (eatertainment, [AT, BR, DE, CH, NL, BE, US])
Farms (farms, All)
Attraction Farms (attractionfarms, [AT, BR, ES, DE, PT, SE, IT, CH, NO, DK, US])
Pick Your Own Farms (pickyourown, [AT, DE, FR, CH, NO, CZ, DK, JP, US])
Ranches (ranches, [CL, ES, CZ, MX, AR, US])
Festivals (festivals, All)
Christmas Markets (xmasmarkets, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, SE, TW])
Fun Fair (funfair, [AT, DE, PT, NL, CH, DK, CZ, NO, BE])
General Festivals (generalfestivals, [AT, DE, CH, PT, JP])
Trade Fairs (tradefairs, [AT, DE, PT, NL, NZ, MX, TR, FI, IT, CH, DK, CZ, NO, BE, JP])
Haunted Houses (hauntedhouses, All)
Jazz & Blues (jazzandblues, All)
LAN Centers (lancenters, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TR, TW, US])
Mah Jong Halls (mahjong, [HK, JP])
Makerspaces (makerspaces, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Marching Bands (marchingbands, [AT, GB, DE, PT, SE, TR, CH, NO])
Museums (museums, All)
Art Museums (artmuseums, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Children's Museums (childrensmuseums, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Music Venues (musicvenues, All)
Observatories (observatories, All)
Opera & Ballet (opera, All)
Pachinko (pachinko, [JP])
Paint & Sip (paintandsip, [HK, US])
Performing Arts (theater, All)
Planetarium (planetarium, All)
Professional Sports Teams (sportsteams, All)
Race Tracks (racetracks, [AR, AU, BE, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Rodeo (rodeo, [US])
Social Clubs (social_clubs, All)
Veterans Organizations (veteransorganizations, [US])
Sports Betting (sportsbetting, [IT, US])
Stadiums & Arenas (stadiumsarenas, All)
Street Art (streetart, [AR, AU, BE, BR, CL, CZ, DE, DK, ES, FR, HK, IT, JP, MX, NL, NO, NZ, PH, PL, PT, SE, TW])
Studio Taping (studiotaping, [NL, BE, US])
Supernatural Readings (psychic_astrology, All)
Astrologers (astrologers, All)
Mystics (mystics, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Psychic Mediums (psychicmediums, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SE, SG, TR, TW, US])
Psychics (psychics, All)
Tablao Flamenco (tablaoflamenco, [CL, ES, PT, MX, AR])
Ticket Sales (ticketsales, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, HK, IT, JP, MX, MY, NO, PH, PT, TW, US])
Virtual Reality Centers (virtualrealitycenters, All)
Wineries (wineries, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Wine Tasting Room (winetastingroom, All)""",

"Automotive" : """Aircraft Dealers (aircraftdealers, [US, PT, CZ])
Aircraft Repairs (aircraftrepairs, All)
Auto Customization (autocustomization, [AT, ES, DE, PT, MX, PL, CL, CA, SG, CH, CZ, AR, US])
Auto Detailing (auto_detailing, [AR, AT, BE, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Auto Electric Services (autoelectric, [BR, ES, PT, MX, CL, IT, CZ, AR])
Auto Glass Services (autoglass, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Car Window Tinting (carwindowtinting, [GB, IE, ES, NL, NZ, AU, BE, IT, SG, CA, US])
Auto Loan Providers (autoloanproviders, [IE, NZ, AU, SG, PT, PH, US, GB, NL, MY, PL, TR, CA, IT, CZ, BE])
Auto Parts & Supplies (autopartssupplies, All)
Motorcycle Parts & Supplies (motorcyclepartsandsupplies, All)
Auto Repair (autorepair, All)
DIY Auto Shop (diyautoshop, [AT, DE, CH, PT, AU, US])
Auto Security (autosecurity, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Auto Upholstery (autoupholstery, All)
Aviation Services (aviationservices, All)
Boat Dealers (boatdealers, [AR, AT, AU, BE, CA, CH, CZ, DE, DK, ES, GB, IE, MX, NL, NO, NZ, PL, PT, SE, SG, US])
Boat Parts & Supplies (boatpartsandsupplies, All)
Body Shops (bodyshops, All)
Car Auctions (carauctions, [TW, SG, PH, HK, MY, US])
Car Brokers (carbrokers, [NZ, AR, AU, US])
Car Buyers (carbuyers, [AT, IE, BR, DE, NZ, AU, CZ, SG, PH, BE, US, GB, NL, MY, PL, CA, CH, NO, DK])
Car Dealers (car_dealers, All)
Car Inspectors (autodamageassessment, [BR, DE, PT, NL, SE, DK, NO, BE, US])
Car Share Services (carshares, [AR, AT, AU, CA, CH, CL, CZ, DE, DK, ES, FR, GB, IE, IT, MX, MY, NO, NZ, PH, PL, SE, US])
Car Stereo Installation (stereo_installation, [AR, AU, BE, BR, CA, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Car Wash (carwash, All)
Commercial Truck Dealers (truckdealers, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SG, US])
Commercial Truck Repair (truckrepair, [AT, IE, BR, ES, DE, NZ, AU, SG, DK, PH, FR, BE, US, GB, NL, MX, MY, PL, CL, CA, IT, CH, NO, AR])
EV Charging Stations (evchargingstations, All)
Fuel Docks (fueldocks, [ES, NO, MX, DK, SE, US])
Gas Stations (servicestations, All)
Golf Cart Dealers (golfcartdealers, [CA, US])
Hybrid Car Repair (hybridcarrepair, [GB, IE, NZ, PL, AU, SE, SG, CZ, US])
Interlock Systems (interlocksystems, [US])
Marinas (marinas, [AT, IE, BR, ES, DE, NZ, AU, SE, SG, DK, FR, BE, US, GB, NL, MX, TR, CL, CA, IT, CH, NO, AR])
Mobile Dent Repair (mobiledentrepair, [CA, US])
Mobility Equipment Sales & Services (mobilityequipment, [CA, US])
Motorcycle Dealers (motorcycledealers, All)
Motorcycle Repair (motorcyclerepair, All)
Motorsport Vehicle Dealers (motodealers, [TW, IT, ES, SE, US])
Motorsport Vehicle Repairs (motorepairs, [TW, IT, ES, SE, US])
Oil Change Stations (oilchange, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
Parking (parking, All)
RV Dealers (rv_dealers, [AT, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, IT, NL, NO, PL, SE, US])
RV Repair (rvrepair, [AT, IE, BR, DE, NZ, AU, SG, DK, PH, PT, BE, US, GB, NL, MY, PL, CH, NO, CA])
Registration Services (registrationservices, [AT, AU, BE, BR, CA, CH, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MY, NL, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Roadside Assistance (roadsideassist, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, IT, JP, MX, MY, NL, NO, PH, PL, US])
Service Stations (service_stations, [AR, AT, AU, BE, CA, CH, CL, DE, ES, GB, IE, IT, MX, NL, NZ, PL, SG, US])
Smog Check Stations (smog_check_stations, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NZ, PH, PL, PT, SG, TR, TW, US])
Tires (tires, All)
Towing (towing, All)
Trailer Dealers (trailerdealers, [GB, IE, DE, NZ, AU, DK, SG, NO, CA, US])
Trailer Rental (trailerrental, All)
Trailer Repair (trailerrepair, [AT, IE, BR, DE, NZ, AU, SE, SG, PH, PT, BE, US, GB, NL, MY, PL, CA, CH, NO, DK])
Transmission Repair (transmissionrepair, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TR, TW, US])
Truck Rental (truck_rental, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, MX, MY, NO, NZ, PH, PL, PT, SG, TW, US])
Used Car Dealers (usedcardealers, All)
Vehicle Shipping (vehicleshipping, All)
Vehicle Wraps (vehiclewraps, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Wheel & Rim Repair (wheelrimrepair, [IT, US, PT])
Windshield Installation & Repair (windshieldinstallrepair, [AR, AU, BE, BR, CA, CL, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])""",

"Beauty & Spas" : """Acne Treatment (acnetreatment, All)
Barbers (barbers, All)
Cosmetics & Beauty Supply (cosmetics, All)
Day Spas (spas, All)
Erotic Massage (eroticmassage, [AR, AT, AU, BE, BR, CA, CH, CZ, DE, ES, FR, GB, IE, IT, MX, NL, NZ, PL, PT, SG])
Eyebrow Services (eyebrowservices, All)
Eyelash Service (eyelashservice, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Foot Care (footcare, [AT, GB, IE, DE, NL, NZ, MY, AU, BE, IT, CH, SG, PH, CA, JP])
Hair Extensions (hair_extensions, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, JP, MX, MY, NO, NZ, PH, PT, SE, SG, TW, US])
Hair Loss Centers (hairloss, All)
Hair Removal (hairremoval, All)
Laser Hair Removal (laser_hair_removal, All)
Sugaring (sugaring, [AT, DE, FI, CH, NO, CZ, DK, US])
Threading Services (threadingservices, All)
Waxing (waxing, All)
Hair Salons (hair, All)
Blow Dry/Out Services (blowoutservices, [GB, IE, PT, AU, TR, CA, DK, NO, CZ, FR, US])
Hair Extensions (hair_extensions, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, JP, MX, MY, NO, NZ, PH, PT, SE, SG, TW, US])
Hair Stylists (hairstylists, [AT, IE, TW, ES, DE, AU, SE, CZ, SG, DK, PT, BE, US, GB, NL, MX, HK, PL, CL, CA, CH, NO, AR])
Kids Hair Salons (kidshairsalons, All)
Men's Hair Salons (menshair, [ES, AR, PT, NL, MX, AU, CL, DK, NO, CZ, BE, US])
Hot Springs (hotsprings, [AT, TW, BR, DE, NZ, AU, CH, CZ, JP, US])
Makeup Artists (makeupartists, All)
Massage (massage, All)
Medical Spas (medicalspa, All)
Aestheticians (aestheticians, [AT, AU, BR, CA, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Nail Salons (othersalons, All)
Nail Technicians (nailtechnicians, [AR, AU, BE, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Perfume (perfume, [AR, AT, AU, BE, BR, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SE, TW, US])
Permanent Makeup (permanentmakeup, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, PH, PL, PT, SE, TR, TW, US])
Piercing (piercing, All)
Skin Care (skincare, All)
Estheticians (estheticians, All)
Tanning (tanning, All)
Spray Tanning (spraytanning, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SG, TR, TW, US])
Tanning Beds (tanningbeds, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SG, TR, TW, US])
Tattoo (tattoo, All)
Teeth Whitening (teethwhitening, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])""",

"Event Planning & Services" : """Balloon Services (balloonservices, [AT, IE, BR, GB, DE, NL, NZ, PL, AU, BE, CH, SG, CA, US])
Bartenders (bartenders, [AR, AU, BE, BR, CA, CL, CZ, DE, DK, ES, FR, IT, MX, NL, PT, SE, US])
Boat Charters (boatcharters, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Cards & Stationery (stationery, All)
Caricatures (caricatures, [BR, ES, PL, SE, IT, SG, NO, DK, US])
Caterers (catering, All)
Clowns (clowns, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, TW, US])
DJs (djs, All)
Face Painting (facepainting, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, GB, IE, NL, NO, NZ, PT, US])
Floral Designers (floraldesigners, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Game Truck Rental (gametruckrental, [CL, CA, MX, AR, US])
Golf Cart Rentals (golfcartrentals, [US])
Henna Artists (hennaartists, [AT, BR, DE, NZ, AU, CA, IT, CH, DK, NO, FR, US])
Hotels (hotels, All)
Agriturismi (agriturismi, [AT, TW, ES, DE, MX, PL, CL, FR, IT, CH, CZ, AR])
Mountain Huts (mountainhuts, [AT, ES, DE, NZ, PL, SE, CL, FR, IT, CH, NO, CZ, AR, US])
Pensions (pensions, [AT, BR, ES, DE, SE, NO, CZ, DK, JP])
Residences (residences, [AT, ES, DE, MY, PL, IT, CH, SG, CZ, PH, US])
Rest Stops (reststops, All)
Ryokan (ryokan, [JP])
Magicians (magicians, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, TW, US])
Mohels (mohels, [US])
Musicians (musicians, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Officiants (officiants, All)
Party & Event Planning (eventplanning, All)
Party Bike Rentals (partybikerentals, [IE, ES, DE, NL, BE, US])
Party Bus Rentals (partybusrentals, [AR, AT, AU, BE, BR, CH, CL, DE, DK, FI, GB, NL, NO, NZ, SE, SG, TR, US])
Party Characters (partycharacters, All)
Party Equipment Rentals (partyequipmentrentals, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, US])
Audio/Visual Equipment Rental (audiovisualequipmentrental, [AT, IE, BR, ES, DE, AU, SE, SG, DK, PH, FR, BE, US, GB, NL, MY, PL, CH, NO, CA])
Bounce House Rentals (bouncehouserentals, [AT, IE, GB, DE, NZ, NL, PL, AU, SE, BE, CH, DK, NO, CA, US])
Karaoke Rental (karaokerental, All)
Party Supplies (partysupplies, All)
Personal Chefs (personalchefs, All)
Photo Booth Rentals (photoboothrentals, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Photographers (photographers, All)
Boudoir Photography (boudoirphotography, [SE, CA, DE, US])
Event Photography (eventphotography, All)
Session Photography (sessionphotography, All)
Silent Disco (silentdisco, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Sommelier Services (sommelierservices, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Team Building Activities (teambuilding, All)
Trivia Hosts (triviahosts, [US])
Valet Services (valetservices, [BR, TR, US])
Venues & Event Spaces (venues, All)
Videographers (videographers, All)
Wedding Chapels (weddingchappels, [US, AU, JP])
Wedding Planning (wedding_planning, All)""",

"Food" : """Acai Bowls (acaibowls, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
Backshop (backshop, [DE, AT, CH])
Bagels (bagels, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bakeries (bakeries, All)
Beer, Wine & Spirits (beer_and_wine, All)
Bento (bento, [JP])
Beverage Store (beverage_stores, [AT, ES, DE, NL, AU, TR, CL, IT, CH, PT, BE, US])
Breweries (breweries, All)
Brewpubs (brewpubs, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, FI, GB, HK, IE, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bubble Tea (bubbletea, [AU, BE, BR, CA, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Butcher (butcher, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
CSA (csa, [AT, DE, CH, FR, US])
Chimney Cakes (chimneycakes, [FR, US, PL, CZ])
Churros (churros, [CL, BR, ES, PT, MX, AR])
Cideries (cideries, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, ES, FI, GB, HK, IE, MX, MY, NZ, PH, PL, PT, SE, SG, TW, US])
Coffee & Tea (coffee, All)
Coffee & Tea Supplies (coffeeteasupplies, [AT, AU, BE, CA, CH, DE, DK, FR, GB, HK, IE, JP, NL, NO, NZ, PL, SE, SG, TR, TW])
Coffee Roasteries (coffeeroasteries, All)
Convenience Stores (convenience, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Cupcakes (cupcakes, [AR, AT, AU, BE, BR, CH, CL, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Custom Cakes (customcakes, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Delicatessen (delicatessen, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
Desserts (desserts, All)
Distilleries (distilleries, All)
Do-It-Yourself Food (diyfood, [AR, AU, BE, BR, CA, DK, GB, HK, IE, JP, MY, NL, NO, PH, PL, PT, SG, TR, TW, US])
Donairs (donairs, [BE, FR, CA, DK, CZ, PL, TR])
Donuts (donuts, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Empanadas (empanadas, [CL, AR, ES, US])
Ethical Grocery (ethicgrocery, [AR, AU, BR, CA, CL, DK, ES, FI, GB, HK, IE, IT, MX, NO, NZ, PL, PT, SE, SG, TW])
Farmers Market (farmersmarket, All)
Fishmonger (fishmonger, [AT, DE, PT, NL, PL, AU, SE, FI, IT, DK, NO, CZ, CH, BE])
Food Delivery Services (fooddeliveryservices, All)
Food Trucks (foodtrucks, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Friterie (friterie, [BE, IT, FR, NL, PL, AU])
Gelato (gelato, [PT, PL, AU, SE, CZ, IT, SG, NO, DK, PH, US])
Grocery (grocery, All)
Hawker Centre (hawkercentre, [TW, HK, MY, MX, CL, SG, PH, AR])
Honey (honey, [DE, PL, SE, TR, FI, IT, FR, US])
Ice Cream & Frozen Yogurt (icecream, All)
Imported Food (importedfood, All)
International Grocery (intlgrocery, All)
Internet Cafes (internetcafe, All)
Japanese Sweets (jpsweets, [JP])
Taiyaki (taiyaki, [JP])
Juice Bars & Smoothies (juicebars, All)
Kiosk (kiosk, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, JP, MX, MY, NL, NO, PH, PL, PT, SE, TR, TW])
Kombucha (kombucha, [US])
Meaderies (meaderies, [AT, ES, DE, MX, PL, CL, CH, AR, US])
Milkshake Bars (milkshakebars, [GB])
Mulled Wine (gluhwein, [AT, DE, CH, CZ, SE])
Nasi Lemak (nasilemak, [MY, SG])
Organic Stores (organic_stores, All)
Panzerotti (panzerotti, [IT])
Parent Cafes (eltern_cafes, [AT, DE, CH])
Patisserie/Cake Shop (cakeshop, All)
Piadina (piadina, [IT, US])
Poke (poke, [AT, IE, BR, DE, NZ, AU, SE, SG, PH, PT, FR, BE, US, GB, NL, MY, PL, CA, CH, NO, DK])
Pretzels (pretzels, [DE, US, CH, PT])
Salumerie (salumerie, [CL, IT, ES, PT, MX, AR])
Shaved Ice (shavedice, [TW, MX, CL, IT, SG, CZ, AR, JP, US])
Shaved Snow (shavedsnow, [TW, SG, HK, CA, MY, US])
Smokehouse (smokehouse, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
Specialty Food (gourmet, All)
Candy Stores (candy, All)
Cheese Shops (cheese, All)
Chocolatiers & Shops (chocolate, All)
Dagashi (dagashi, [JP])
Dried Fruit (driedfruit, [TW, BR, ES, HK, MX, PL, SE, TR, CL, CZ, AR, JP])
Frozen Food (frozenfood, [GB, IT, FR, ES, SG, BE])
Fruits & Veggies (markets, All)
Health Markets (healthmarkets, All)
Herbs & Spices (herbsandspices, All)
Macarons (macarons, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TR, TW, US])
Meat Shops (meats, All)
Olive Oil (oliveoil, [AT, FR, ES, DE, BE, US])
Pasta Shops (pastashops, [GB, IE, AR, NL, NZ, AU, CL, IT, DK, NO, CZ, SG, BE, JP, US])
Popcorn Shops (popcorn, [GB, JP, US])
Seafood Markets (seafoodmarkets, All)
Tofu Shops (tofu, [JP])
Street Vendors (streetvendors, All)
Sugar Shacks (sugarshacks, [CA])
Tea Rooms (tea, All)
Torshi (torshi, [TR])
Tortillas (tortillas, [MX])
Water Stores (waterstores, [BR, MX, CA, US])
Wineries (wineries, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Wine Tasting Room (winetastingroom, All)
Zapiekanka (zapiekanka, [PL])""",

"Health & Medical" : """Acupuncture (acupuncture, All)
Alternative Medicine (alternativemedicine, [AU, BE, BR, CA, CZ, DK, FR, GB, IE, IT, NL, NO, NZ, SE, SG, US])
Animal Assisted Therapy (animalassistedtherapy, All)
Assisted Living Facilities (assistedliving, All)
Ayurveda (ayurveda, All)
Behavior Analysts (behavioranalysts, All)
Blood & Plasma Donation Centers (blooddonation, [AR, AT, AU, BR, CH, CL, CZ, DE, DK, ES, FI, FR, IT, JP, MX, NO, NZ, PL, PT, SE, TR, US])
Body Contouring (bodycontouring, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Cannabis Clinics (cannabis_clinics, [GB, IE, NL, PL, TR, IT, CA, US])
Cannabis Tours (cannabistours, [CA, US])
Cannabis Collective (cannabiscollective, [CA, US])
Chiropractors (chiropractors, All)
Colonics (colonics, [GB, IE, NZ, AU, DK, SG, NO, CA, US])
Concierge Medicine (conciergemedicine, [US])
Counseling & Mental Health (c_and_mh, All)
Psychoanalysts (psychoanalysts, [BR, ES, AR, PT, NL, MX, FR, CZ, BE])
Psychologists (psychologists, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, IT, MX, MY, NL, NO, NZ, PH, PT, SE, TR, TW, US])
Psychotherapists (psychotherapists, [AT, BR, DE, FI, FR, CH, NO, CZ, SG, DK])
Sex Therapists (sextherapists, All)
Sophrologists (sophrologists, [FR, BE, PL, CZ])
Sports Psychologists (sportspsychologists, [NZ, IT, SG, US])
Crisis Pregnancy Centers (crisispregnancycenters, [US])
Cryotherapy (cryotherapy, [IT, US])
Dental Hygienists (dentalhygienists, [CA, DE, NO, PT, NL, DK, US])
Mobile Clinics (dentalhygienistsmobile, [CA])
Storefront Clinics (dentalhygeiniststorefront, [CA])
Dentists (dentists, All)
Cosmetic Dentists (cosmeticdentists, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Endodontists (endodontists, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
General Dentistry (generaldentistry, All)
Oral Surgeons (oralsurgeons, All)
Orthodontists (orthodontists, All)
Pediatric Dentists (pediatric_dentists, All)
Periodontists (periodontists, All)
Diagnostic Services (diagnosticservices, All)
Diagnostic Imaging (diagnosticimaging, [GB, IE, BR, ES, AR, MX, AU, CL, FR, PT, CA, US])
Laboratory Testing (laboratorytesting, [BR, ES, AR, PT, MX, PL, AU, CL, FR, IT, CA, CZ, BE, US])
Dialysis Clinics (dialysisclinics, [BR, ES, MX, TR, CL, IT, PT, AR, US])
Dietitians (dietitians, All)
Doctors (physicians, All)
Addiction Medicine (addictionmedicine, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Allergists (allergist, All)
Anesthesiologists (anesthesiologists, [IT, FR, PT, BE, AU, SE, US])
Audiologist (audiologist, [AR, AU, BE, BR, CA, CL, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Cardiologists (cardiology, All)
Cosmetic Surgeons (cosmeticsurgeons, All)
Dermatologists (dermatology, All)
Ear Nose & Throat (earnosethroat, All)
Emergency Medicine (emergencymedicine, All)
Endocrinologists (endocrinologists, [AR, AT, BE, BR, CH, CL, CZ, DE, DK, ES, FR, IT, MX, MY, NL, NO, PH, PT, TR, US])
Family Practice (familydr, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Fertility (fertility, All)
Gastroenterologist (gastroenterologist, All)
Geneticists (geneticists, All)
Gerontologists (gerontologist, All)
Hepatologists (hepatologists, All)
Homeopathic (homeopathic, [AR, AT, BE, BR, CH, CL, CZ, DE, DK, ES, FI, FR, IT, JP, MX, MY, NL, NO, PH, PL, PT, SE])
Hospitalists (hospitalists, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Immunodermatologists (immunodermatologists, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Infectious Disease Specialists (infectiousdisease, All)
Internal Medicine (internalmed, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Naturopathic/Holistic (naturopathic, All)
Nephrologists (nephrologists, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Neurologist (neurologist, All)
Neuropathologists (neuropathologists, All)
Neurotologists (neurotologists, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Obstetricians & Gynecologists (obgyn, All)
Oncologist (oncologist, All)
Ophthalmologists (opthamalogists, All)
Retina Specialists (retinaspecialists, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Orthopedists (orthopedists, All)
Osteopathic Physicians (osteopathicphysicians, All)
Otologists (otologists, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Pain Management (painmanagement, All)
Pathologists (pathologists, All)
Pediatricians (pediatricians, All)
Phlebologists (phlebologists, All)
Plastic Surgeons (plasticsurgeons, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Podiatrists (podiatrists, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Preventive Medicine (preventivemedicine, All)
Proctologists (proctologist, All)
Psychiatrists (psychiatrists, All)
Pulmonologist (pulmonologist, All)
Radiologists (radiologists, All)
Rheumatologists (rhematologists, [AR, AT, BE, BR, CH, CL, CZ, DE, DK, ES, FR, IT, MX, MY, NL, NO, PH, PT, SE, US])
Spine Surgeons (spinesurgeons, [US])
Sports Medicine (sportsmed, All)
Surgeons (surgeons, All)
Tattoo Removal (tattooremoval, All)
Toxicologists (toxicologists, All)
Tropical Medicine (tropicalmedicine, [AT, BR, IT, DE, CH, NL, BE])
Undersea/Hyperbaric Medicine (underseamedicine, All)
Urologists (urologists, All)
Vascular Medicine (vascularmedicine, All)
Doulas (doulas, [CA, FR, IT, PT, BE, US, CZ])
Emergency Rooms (emergencyrooms, All)
Float Spa (floatspa, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Habilitative Services (habilitativeservices, All)
Halfway Houses (halfwayhouses, [US])
Halotherapy (halotherapy, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Health Coach (healthcoach, All)
Health Insurance Offices (healthinsurance, [AT, BR, DE, PT, NZ, MX, PL, AU, FR, SG, CH, CZ, BE, US])
Hearing Aid Providers (hearingaidproviders, [AU, BE, BR, CA, DK, FI, FR, GB, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SG, TW, US])
Hearing Aids (hearing_aids, [AT, BR, ES, DE, PT, MX, PL, FI, CL, FR, CH, DK, CZ, NO, AR])
Herbal Shops (herbalshops, All)
Home Health Care (homehealthcare, All)
Hospice (hospice, All)
Hospitals (hospitals, All)
Hydrotherapy (hydrotherapy, All)
Hypnosis/Hypnotherapy (hypnosis, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, JP, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TW, US])
IV Hydration (ivhydration, [US])
Lactation Services (lactationservices, [BE, BR, IT, PT, FR, US])
Laser Eye Surgery/Lasik (laserlasikeyes, All)
Lice Services (liceservices, [AT, AU, BE, BR, CA, CH, DK, ES, FR, GB, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Massage Therapy (massage_therapy, [AR, AU, BE, BR, CA, CL, DK, ES, GB, IT, JP, MX, NL, NO, PT, US])
Medical Cannabis Referrals (cannabisreferrals, [CA, US])
Medical Centers (medcenters, All)
Bulk Billing (bulkbilling, [AU])
Osteopaths (osteopaths, [AU])
Walk-in Clinics (walkinclinics, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Medical Foot Care (medicalfoot, [AU, BE, CA, CH, DE, DK, FR, GB, HK, IE, NL, NO, NZ, SE, SG, TW])
Medical Spas (medicalspa, All)
Aestheticians (aestheticians, [AT, AU, BR, CA, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Medical Transportation (medicaltransportation, [AT, BR, DE, PT, NL, AU, FR, IT, CH, DK, NO, SG, BE, US])
Memory Care (memorycare, All)
Midwives (midwives, All)
Nurse Practitioner (nursepractitioner, All)
Nutritionists (nutritionists, All)
Occupational Therapy (occupationaltherapy, [AR, AU, BE, BR, CA, CL, DE, DK, ES, GB, IE, MX, NL, NO, PT, US])
Optometrists (optometrists, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Organ & Tissue Donor Services (organdonorservices, [US])
Orthotics (orthotics, [GB, IE, BR, ES, NZ, AU, FI, FR, IT, NO, SG, CZ, DK, US])
Oxygen Bars (oxygenbars, [US])
Personal Care Services (personalcare, [BR, NL, PL, AU, FI, FR, DK, NO, CZ, BE, US])
Pharmacy (pharmacy, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Physical Therapy (physicaltherapy, All)
Placenta Encapsulations (placentaencapsulation, [AR, AU, BE, BR, CA, CL, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
Postpartum Care (postpartumcare, [TW, HK, MY, PL, JP])
Prenatal/Perinatal Care (prenatal, [AR, AU, BE, BR, CL, CZ, DK, ES, FI, FR, IT, MX, NL, NO, NZ, PT, SE, US])
Prosthetics (prosthetics, [ES, IT, AU, US])
Prosthodontists (prosthodontists, [IT, ES, US])
Psychotechnical Tests (psychotechnicaltests, [BR, ES])
Reflexology (reflexology, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SG, TW, US])
Rehabilitation Center (rehabilitation_center, [AR, AU, BE, BR, CA, CL, CZ, DE, DK, ES, FI, GB, IE, IT, JP, MX, NL, NO, NZ, PL, PT, SE, US])
Reiki (reiki, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Reproductive Health Services (reproductivehealthservices, All)
Retirement Homes (retirement_homes, All)
Saunas (saunas, [AR, AT, BE, BR, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, NL, NO, PT, SE, TR, TW, US])
Skilled Nursing (skillednursing, [US])
Sleep Specialists (sleepspecialists, All)
Speech Therapists (speech_therapists, All)
Sperm Clinic (spermclinic, [ES, AR, DE, NL, MX, CL, FR, IT, DK, NO, BE, US])
Traditional Chinese Medicine (tcm, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Tui Na (tuina, All)
Ultrasound Imaging Centers (ultrasoundimagingcenters, All)
Urgent Care (urgent_care, All)
Weight Loss Centers (weightlosscenters, All)""",

'Hotel & Travel' : """Airports (airports, All)
Airport Terminals (airportterminals, All)
Bed & Breakfast (bedbreakfast, All)
Campgrounds (campgrounds, All)
Car Rental (carrental, All)
Guest Houses (guesthouses, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Health Retreats (healthretreats, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Hostels (hostels, All)
Hotels (hotels, All)
Agriturismi (agriturismi, [AT, TW, ES, DE, MX, PL, CL, FR, IT, CH, CZ, AR])
Mountain Huts (mountainhuts, [AT, ES, DE, NZ, PL, SE, CL, FR, IT, CH, NO, CZ, AR, US])
Pensions (pensions, [AT, BR, ES, DE, SE, NO, CZ, DK, JP])
Residences (residences, [AT, ES, DE, MY, PL, IT, CH, SG, CZ, PH, US])
Rest Stops (reststops, All)
Ryokan (ryokan, [JP])
Motorcycle Rental (motorcycle_rental, [BR, ES, DE, PT, NZ, MX, AU, FI, IT, NO, SG, CZ, FR, US])
RV Parks (rvparks, [AT, IE, ES, DE, NZ, AU, SE, CZ, SG, DK, FR, BE, US, GB, NL, MX, PL, TR, FI, CL, CA, IT, CH, NO, AR])
RV Rental (rvrental, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Resorts (resorts, All)
Ski Resorts (skiresorts, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Tours (tours, All)
Aerial Tours (aerialtours, All)
Architectural Tours (architecturaltours, All)
Art Tours (arttours, All)
Beer Tours (beertours, All)
Bike tours (biketours, All)
Boat Tours (boattours, All)
Bus Tours (bustours, All)
Food Tours (foodtours, All)
Historical Tours (historicaltours, All)
Scooter Tours (scootertours, All)
Walking Tours (walkingtours, All)
Whale Watching Tours (whalewatchingtours, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Wine Tours (winetours, All)
Train Stations (trainstations, All)
Transportation (transport, All)
Airlines (airlines, All)
Airport Shuttles (airport_shuttles, All)
Bike Sharing (bikesharing, All)
Bus Stations (busstations, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Buses (buses, All)
Cable Cars (cablecars, [AT, BR, DE, PT, NZ, TR, IT, CH, CZ, FR, JP, US])
Dolmus Station (dolmusstation, [TR])
Ferries (ferries, All)
Limos (limos, All)
Metro Stations (metrostations, All)
Pedicabs (pedicabs, [AT, DE, MY, SE, CH, NO, DK, PH, US])
Private Jet Charter (privatejetcharter, All)
Public Transportation (publictransport, All)
Shared Taxis (sharedtaxis, [BR, TR, NO, DK, PH, SE])
Taxis (taxis, All)
Town Car Service (towncarservice, [GB, IE, TW, NL, NZ, MY, HK, AU, CA, SG, PH, BE, US])
Trains (trains, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, FR, GB, IE, NL, NO, PL, PT, SE, US])
Water Taxis (watertaxis, [GB, IE, IT, NZ, MX, AU])
Travel Services (travelservices, All)
Luggage Storage (luggagestorage, All)
Passport & Visa Services (passportvisaservices, All)
Travel Agents (travelagents, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Visitor Centers (visitorcenters, All)
Vacation Rental Agents (vacationrentalagents, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Vacation Rentals (vacation_rentals, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])""",

'Local Services' : """3D Printing (3dprinting, All)
Adoption Services (adoptionservices, All)
Air Duct Cleaning (airductcleaning, [GB, IE, ES, NZ, MY, AU, IT, SG, PH, CA, US])
Appliances & Repair (homeappliancerepair, All)
Appraisal Services (appraisalservices, All)
Art Installation (artinstallation, [AT, DE, CH, PH, MY, PL, US])
Art Restoration (artrestoration, All)
Awnings (awnings, All)
Bail Bondsmen (bailbondsmen, [US, PT])
Bike Repair/Maintenance (bike_repair_maintenance, All)
Biohazard Cleanup (biohazardcleanup, All)
Bookbinding (bookbinding, All)
Bus Rental (busrental, All)
Calligraphy (calligraphy, [BR, IT, ES, NL, BE, TR, US])
Carpet Cleaning (carpet_cleaning, All)
Carpet Dyeing (carpetdyeing, [GB, IE, NZ, MY, PL, AU, SG, PH, CA, US])
Child Care & Day Care (childcare, All)
Clock Repair (clockrepair, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Community Book Box (communitybookbox, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, FI, GB, HK, IE, NL, NO, NZ, PL, PT, SE, SG, TR, TW, US])
Community Gardens (communitygardens, [IE, BR, ES, DE, NZ, AU, SE, SG, DK, PT, FR, US, GB, IT, NO, CA])
Community Service/Non-Profit (nonprofit, All)
Food Banks (foodbanks, All)
Homeless Shelters (homelessshelters, [US])
Couriers & Delivery Services (couriers, All)
Crane Services (craneservices, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, GB, IE, IT, MX, NL, NO, NZ, PL, PT, SE, SG, US])
Donation Center (donationcenter, [AT, BR, ES, DE, NL, CH, DK, NO, BE, US])
Elder Care Planning (eldercareplanning, All)
Electronics Repair (electronicsrepair, All)
Elevator Services (elevatorservices, [AT, AU, BE, BR, CA, CH, DE, DK, ES, GB, HK, IE, IT, NL, NO, NZ, PL, PT, SE, SG, TR, TW, US])
Engraving (engraving, All)
Environmental Abatement (enviroabatement, All)
Environmental Testing (environmentaltesting, [GB, IE, NL, NZ, AU, FI, BE, DK, SG, NO, CA, US])
Farm Equipment Repair (farmequipmentrepair, All)
Fingerprinting (fingerprinting, [US])
Forestry (forestry, [FI, CA, NO, CZ, DK, SE])
Funeral Services & Cemeteries (funeralservices, All)
Cremation Services (cremationservices, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Mortuary Services (mortuaryservices, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Furniture Rental (rentfurniture, [ES, AR, NL, MX, AU, CL, CA, PT, BE, JP, US])
Furniture Repair (furniturerepair, All)
Furniture Reupholstery (reupholstery, All)
Generator Installation/Repair (generatorinstallrepair, [US])
Gestorias (gestorias, [CL, MX, AR, ES])
Grill Services (grillservices, [AT, BR, ES, DE, MX, PL, CL, CH, PT, AR, US])
Gunsmith (gunsmith, [AR, AU, CA, CL, CZ, DK, ES, FI, FR, GB, IE, IT, MX, MY, NO, NZ, PH, PL, PT, SE, SG, US])
Hazardous Waste Disposal (hazardouswastedisposal, [AR, AU, BE, CA, CL, DK, ES, FI, GB, IE, IT, MX, NL, NO, NZ, PL, SG, TW, US])
Hydro-jetting (hydrojetting, [US, CZ])
IT Services & Computer Repair (itservices, All)
Data Recovery (datarecovery, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, IE, IT, MX, NO, NZ, PL, PT, SE, SG, TR, US])
Mobile Phone Repair (mobilephonerepair, All)
Telecommunications (telecommunications, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Ice Delivery (icedelivery, All)
Internet Booths & Calling Centers (internetbooth, [CL, BR, IT, ES, MX, AR])
Jewelry Repair (jewelryrepair, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FR, IT, JP, MX, MY, NL, NO, PH, PL, PT, TR, US])
Junk Removal & Hauling (junkremovalandhauling, All)
Dumpster Rental (dumpsterrental, [AT, IE, DE, NZ, AU, DK, SG, PH, US, GB, NL, HK, MY, PL, CA, CH, NO, BE])
Junkyards (junkyards, [AT, IE, BR, DE, NZ, AU, SE, DK, SG, FR, US, GB, NL, PL, CA, NO, CZ, BE])
Knife Sharpening (knifesharpening, All)
Laundry Services (laundryservices, All)
Dry Cleaning (dryclean, All)
Laundromat (laundromat, All)
Machine & Tool Rental (machinerental, All)
Machine Shops (machineshops, [US])
Mailbox Centers (mailboxcenters, [US])
Metal Detector Services (metaldetectorservices, All)
Metal Fabricators (metalfabricators, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
Misting System Services (mistingsystemservices, [US])
Musical Instrument Services (musicinstrumentservices, All)
Guitar Stores (guitarstores, All)
Piano Services (pianoservices, All)
Piano Stores (pianostores, All)
Vocal Coach (vocalcoach, All)
Nanny Services (nannys, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
Notaries (notaries, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Outdoor Power Equipment Services (outdoorpowerequipmentservices, [AT, BR, DE, PT, MY, PL, CH, DK, NO, CA, PH, US])
Pest Control (pest_control, All)
Portable Toilet Services (portabletoiletservices, [AT, AU, BE, BR, CA, CH, DE, DK, ES, GB, IE, IT, NL, NO, NZ, PL, PT, SE, SG, TR, US])
Powder Coating (powdercoating, [US])
Printing Services (copyshops, All)
Propane (propane, [AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, PH, PL, PT, SE, SG, TR, TW, US])
Record Labels (record_labels, [AT, BR, DE, PT, CH, NO, CZ, DK])
Recording & Rehearsal Studios (recording_studios, All)
Recycling Center (recyclingcenter, All)
Sandblasting (sandblasting, [AT, BR, ES, DE, NL, IT, CH, BE, US])
Screen Printing (screenprinting, All)
Screen Printing/T-Shirt Printing (screen_printing_tshirt_printing, [AR, AT, AU, BE, BR, CH, CL, DE, DK, ES, FR, JP, MX, MY, NL, NO, PH, PT, SE, US])
Self Storage (selfstorage, All)
Septic Services (septicservices, [BR, PT, NL, PL, BE, DK, NO, CA, US])
Sewing & Alterations (sewingalterations, All)
Shipping Centers (shipping_centers, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NZ, PH, PL, PT, SG, TR, TW, US])
Shoe Repair (shoerepair, All)
Shoe Shine (shoeshine, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Smoking Areas (smokingareas, [JP])
Snow Removal (snowremoval, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, JP, MY, NL, NO, PH, PL, PT, SE, SG, TR, TW, US])
Snuggle Services (snuggleservices, [JP, US])
Stonemasons (stonemasons, All)
TV Mounting (tvmounting, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Watch Repair (watch_repair, All)
Water Delivery (waterdelivery, [BR, PH, HK, CA, MY, US])
Well Drilling (welldrilling, [AT, BR, ES, DE, AR, CZ, PH, US, MX, PL, MY, CL, IT, CH, NO, DK])
Wildlife Control (wildlifecontrol, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Youth Club (youth_club, [IE, DE, NZ, AU, SE, DK, SG, PT, FR, GB, NL, FI, CA, IT, CH, NO, CZ, BE])""",

'Nightlife' : """Adult Entertainment (adultentertainment, All)
Strip Clubs (stripclubs, All)
Striptease Dancers (stripteasedancers, All)
Bar Crawl (barcrawl, [AT, DE, MX, PL, AU, CH, CZ, AR, US])
Bars (bars, All)
Absinthe Bars (absinthebars, [CZ])
Airport Lounges (airportlounges, All)
Beach Bars (beachbars, [AR, AT, AU, BR, CH, CL, DE, DK, ES, FR, IT, MX, NL, NO, PT, SE, SG])
Beer Bar (beerbar, All)
Champagne Bars (champagne_bars, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Cigar Bars (cigarbars, [US])
Cocktail Bars (cocktailbars, All)
Dive Bars (divebars, [AR, AT, BR, CA, CH, CL, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Drive-Thru Bars (drivethrubars, [US])
Gay Bars (gaybars, All)
Hookah Bars (hookah_bars, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Hotel bar (hotel_bar, [FI, BR, PT, NO, DK, SE])
Irish Pub (irish_pubs, All)
Lounges (lounges, All)
Pubs (pubs, All)
Pulquerias (pulquerias, [MX])
Sake Bars (sakebars, [JP])
Speakeasies (speakeasies, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NZ, PH, PL, PT, SE, SG, TW, US])
Sports Bars (sportsbars, [AR, AU, BE, BR, CA, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Tabac (tabac, [IT, FR, ES, CZ, BE])
Tiki Bars (tikibars, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
Vermouth Bars (vermouthbars, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, ES, FI, GB, HK, IE, MX, MY, NL, NZ, PH, PT, SE, SG, TW, US])
Whiskey Bars (whiskeybars, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Wine Bars (wine_bars, All)
Beer Gardens (beergardens, [GB, IE, MX, PL, AU, SE, CA, IT, DK, NO, CZ, FR, JP, US])
Club Crawl (clubcrawl, [US])
Coffeeshops (coffeeshops, [NL, PT])
Comedy Clubs (comedyclubs, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Country Dance Halls (countrydancehalls, [SE, US])
Dance Clubs (danceclubs, All)
Dance Restaurants (dancerestaurants, [FI])
Fasil Music (fasil, [TR])
Jazz & Blues (jazzandblues, All)
Karaoke (karaoke, All)
Music Venues (musicvenues, All)
Piano Bars (pianobars, [AR, BE, CA, CL, CZ, DE, DK, FR, GB, HK, IT, JP, MX, MY, NL, NO, PH, PT, SE, TR, TW, US])
Pool Halls (poolhalls, All)""",

"Restaurants" : """Afghan (afghani, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
African (african, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Senegalese (senegalese, [CA, FR, IT, BE, US])
South African (southafrican, [CA, FR, IT, BE, AU, US])
American (New) (newamerican, [GB, IE, NO, DK, SE, US])
American (Traditional) (tradamerican, All)
Andalusian (andalusian, [IT, ES])
Arabic (arabian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Arab Pizza (arabpizza, [BR])
Argentine (argentine, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Armenian (armenian, [GB, ES, AR, PL, TR, FR, IT, CZ, BE, US])
Asian Fusion (asianfusion, All)
Asturian (asturian, [ES])
Australian (australian, All)
Austrian (austrian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Baguettes (baguettes, [DE, PT, MX, SE, TR, CZ, IT, NO])
Bangladeshi (bangladeshi, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Barbeque (bbq, [AR, AT, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Basque (basque, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
Bavarian (bavarian, [AT, DE, CH])
Beer Garden (beergarden, [AT, DE, CH, CZ])
Beer Hall (beerhall, [AT, DE, CH])
Beisl (beisl, [AT])
Belgian (belgian, All)
Flemish (flemish, [FR])
Bistros (bistros, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
Black Sea (blacksea, [TR])
Brasseries (brasseries, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Brazilian (brazilian, All)
Brazilian Empanadas (brazilianempanadas, [BR])
Central Brazilian (centralbrazilian, [BR])
Northeastern Brazilian (northeasternbrazilian, [BR])
Northern Brazilian (northernbrazilian, [BR])
Rodizios (rodizios, [BR, AR, PT])
Breakfast & Brunch (breakfast_brunch, All)
Pancakes (pancakes, All)
British (british, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Buffets (buffets, All)
Bulgarian (bulgarian, [AR, AT, AU, BE, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, PH, PL, PT, SE, TW, US])
Burgers (burgers, All)
Burmese (burmese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Cafes (cafes, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Themed Cafes (themedcafes, [AT, TW, IE, AR, DE, NZ, AU, SE, SG, DK, PH, FR, JP, BE, US, GB, NL, HK, MY, MX, PL, FI, CL, CH, NO, CA])
Cafeteria (cafeteria, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, TR, TW, US])
Cajun/Creole (cajun, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TR, TW, US])
Cambodian (cambodian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Canadian (New) (newcanadian, [CA])
Canteen (canteen, [AT, DE, NL, PL, FI, IT, CH, DK, CZ, NO, BE, JP])
Caribbean (caribbean, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Dominican (dominican, [US])
Haitian (haitian, [CA, US])
Puerto Rican (puertorican, [US])
Trinidadian (trinidadian, [US])
Catalan (catalan, [ES, AR, MX, TR, CL, IT, PT, FR, US])
Cheesesteaks (cheesesteaks, [GB, IE, CA, NL, PL, AU, US])
Chicken Shop (chickenshop, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Chicken Wings (chicken_wings, [AR, AT, AU, BR, CA, CZ, DE, GB, HK, IE, MX, MY, NZ, PH, PL, SE, SG, TR, TW, US])
Chilean (chilean, [FI, CL, BR, FR])
Chinese (chinese, All)
Cantonese (cantonese, [TW, NZ, AU, SE, SG, BE, FR, JP, US, GB, NL, HK, MY, CA, IT, AR])
Congee (congee, [TW, HK, MY, SG])
Dim Sum (dimsum, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Fuzhou (fuzhou, [TW, HK, MY, SG])
Hainan (hainan, [SG, PH, HK, MY, US])
Hakka (hakka, [TW, SG, PH, HK, CA, MY])
Henghwa (henghwa, [TW, HK, MY, SG])
Hokkien (hokkien, [TW, HK, MY, SG])
Hunan (hunan, [TW, SG, HK, FR, MY])
Pekinese (pekinese, [TW, IT, SG, HK, MY, FR, JP])
Shanghainese (shanghainese, [TW, HK, MY, AU, SE, BE, IT, SG, FR, JP, US])
Szechuan (szechuan, [GB, IE, TW, NZ, HK, MY, AU, SG, FR, JP, US])
Teochew (teochew, [TW, HK, MY, SG])
Comfort Food (comfortfood, [FI, CL, CA, MX, AR, JP, US])
Corsican (corsican, [FR, BE])
Creperies (creperies, All)
Cuban (cuban, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
Curry Sausage (currysausage, [AT, DE, CH])
Cypriot (cypriot, [AT, DE, CH])
Czech (czech, [GB, IE, DE, PL, AU, SE, FI, BE, FR, IT, DK, NO, CZ, CA, US])
Czech/Slovakian (czechslovakian, [MX, AR, PT])
Danish (danish, [FR, DK, SE, NO])
Delis (delis, [AR, AT, AU, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NO, NZ, PH, PL, SG, TR, TW, US])
Diners (diners, [AR, AT, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
Dinner Theater (dinnertheater, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Dumplings (dumplings, [GB, IE, AT, DE, NL, NZ, PL, AU, CA, SG, CH, BE, JP])
Eastern European (eastern_european, [FR, NO, CZ, DK, AU])
Eritrean (eritrean, [AT, IT, DE, CH, US])
Ethiopian (ethiopian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
Fast Food (hotdogs, All)
Filipino (filipino, [AR, AT, AU, BE, BR, CA, CH, CL, DE, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Fischbroetchen (fischbroetchen, [DE])
Fish & Chips (fishnchips, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Flatbread (flatbread, [AT, DE, CH, DK, PL])
Fondue (fondue, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Food Court (food_court, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, US])
Food Stands (foodstands, All)
Freiduria (freiduria, [CL, MX, AR, ES])
French (french, All)
Alsatian (alsatian, [FR, DE])
Auvergnat (auvergnat, [FR])
Berrichon (berrichon, [FR])
Bourguignon (bourguignon, [FR])
Mauritius (mauritius, [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
Nicoise (nicois, [FR])
Provencal (provencal, [FR])
Reunion (reunion, [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
French Southwest (sud_ouest, [FR, BE])
Galician (galician, [ES, PT])
Game Meat (gamemeat, [AT, AU, BE, CH, CZ, DE, DK, ES, FR, GB, IE, IT, NL, NO, NZ, PL, SE, SG, US])
Gastropubs (gastropubs, All)
Georgian (georgian, [AT, GB, DE, PL, FI, CH, CZ, US])
German (german, All)
Baden (baden, [DE])
Eastern German (easterngerman, [DE])
Franconian (franconian, [DE])
Hessian (hessian, [DE])
Northern German (northerngerman, [DE])
Palatine (palatine, [DE])
Rhinelandian (rhinelandian, [DE])
Giblets (giblets, [TR])
Gluten-Free (gluten_free, All)
Greek (greek, All)
Guamanian (guamanian, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
Halal (halal, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Hawaiian (hawaiian, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Heuriger (heuriger, [AT])
Himalayan/Nepalese (himalayan, All)
Honduran (honduran, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Hong Kong Style Cafe (hkcafe, [TW, HK, CA, US])
Hot Dogs (hotdog, All)
Hot Pot (hotpot, [TW, BR, HK, MY, SE, FR, SG, PH, CA, JP, US])
Hungarian (hungarian, All)
Iberian (iberian, [CA, US, PT])
Indian (indpak, All)
Indonesian (indonesian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
International (international, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TW])
Irish (irish, All)
Island Pub (island_pub, [SE])
Israeli (israeli, [AT, DE, CH, CZ])
Italian (italian, All)
Abruzzese (abruzzese, [IT])
Altoatesine (altoatesine, [IT])
Apulian (apulian, [IT, FR])
Calabrian (calabrian, [IT, FR, US])
Cucina campana (cucinacampana, [IT])
Emilian (emilian, [IT])
Friulan (friulan, [IT])
Ligurian (ligurian, [IT, FR])
Lumbard (lumbard, [IT])
Napoletana (napoletana, [IT, FR, CZ])
Piemonte (piemonte, [IT, FR])
Roman (roman, [IT, FR, JP])
Sardinian (sardinian, [IT, FR, US])
Sicilian (sicilian, [IT, FR, CZ, PL, US])
Tuscan (tuscan, [IT, FR, US])
Venetian (venetian, [IT, FR])
Japanese (japanese, All)
Blowfish (blowfish, [JP])
Conveyor Belt Sushi (conveyorsushi, [AT, TW, DE, NL, HK, PL, SE, IT, CH, SG, BE, JP, US])
Donburi (donburi, [TW, HK, JP])
Gyudon (gyudon, [JP])
Oyakodon (oyakodon, [JP])
Hand Rolls (handrolls, [TW, BR])
Horumon (horumon, [TW, JP])
Izakaya (izakaya, [TW, BR, NZ, HK, MX, AU, SG, JP, US])
Japanese Curry (japacurry, [TW, SG, HK, JP, US])
Kaiseki (kaiseki, [TW, JP])
Kushikatsu (kushikatsu, [JP])
Oden (oden, [TW, JP])
Okinawan (okinawan, [JP])
Okonomiyaki (okonomiyaki, [TW, JP])
Onigiri (onigiri, [TW, JP])
Ramen (ramen, All)
Robatayaki (robatayaki, [TW, HK, JP])
Soba (soba, [TW, JP])
Sukiyaki (sukiyaki, [TW, JP])
Takoyaki (takoyaki, [TW, JP])
Tempura (tempura, [TW, JP, SG])
Teppanyaki (teppanyaki, [TW, NZ, MX, HK, AU, SG, JP, US])
Tonkatsu (tonkatsu, [TW, JP, SG])
Udon (udon, [FI, TW, NO, HK, DK, JP, SE])
Unagi (unagi, [TW, JP])
Western Style Japanese Food (westernjapanese, [TW, JP, SG])
Yakiniku (yakiniku, [TW, JP, SG])
Yakitori (yakitori, [TW, JP, SG])
Jewish (jewish, [IT, PL, DE])
Kebab (kebab, All)
Kopitiam (kopitiam, [MY, SG])
Korean (korean, All)
Kosher (kosher, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Kurdish (kurdish, [SE, NO])
Laos (laos, [AU])
Laotian (laotian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Latin American (latin, All)
Colombian (colombian, [ES, AR, MX, FI, CL, CA, FR, BE, US])
Salvadoran (salvadoran, [CA, US])
Venezuelan (venezuelan, [CL, FR, CA, ES, PT, AR, US])
Live/Raw Food (raw_food, All)
Lyonnais (lyonnais, [FR, BE])
Malaysian (malaysian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Mamak (mamak, [MY, AU])
Nyonya (nyonya, [MY, AU])
Meatballs (meatballs, [NL, FR, BE, TR])
Mediterranean (mediterranean, All)
Falafel (falafel, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Mexican (mexican, All)
Eastern Mexican (easternmexican, [MX])
Jaliscan (jaliscan, [MX])
Northern Mexican (northernmexican, [MX])
Oaxacan (oaxacan, [MX])
Pueblan (pueblan, [MX])
Tacos (tacos, [MX, US])
Tamales (tamales, [MX])
Yucatan (yucatan, [MX])
Middle Eastern (mideastern, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Egyptian (egyptian, [CA, FR, IT, BE, US])
Lebanese (lebanese, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Milk Bars (milkbars, [PL, AU])
Modern Australian (modern_australian, [AU])
Modern European (modern_european, All)
Mongolian (mongolian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Moroccan (moroccan, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
New Mexican Cuisine (newmexican, [US])
New Zealand (newzealand, [NZ])
Nicaraguan (nicaraguan, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Night Food (nightfood, [DK, TR, NO, PL, SE])
Nikkei (nikkei, [CL, BR, ES, MX, AR])
Noodles (noodles, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Norcinerie (norcinerie, [IT])
Open Sandwiches (opensandwiches, [DK, SE, TR, NO])
Oriental (oriental, [AT, FR, DE, CH, PT, PL])
PF/Comercial (pfcomercial, [BR])
Pakistani (pakistani, All)
Pan Asian (panasian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Parent Cafes (eltern_cafes, [AT, DE, CH])
Parma (parma, [AU])
Persian/Iranian (persian, All)
Peruvian (peruvian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
Pita (pita, [TR])
Pizza (pizza, All)
Polish (polish, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Pierogis (pierogis, [PL])
Polynesian (polynesian, [US])
Pop-Up Restaurants (popuprestaurants, [TW, IE, DE, NZ, AU, SE, DK, SG, PH, FR, US, GB, NL, MY, HK, CA, NO, BE])
Portuguese (portuguese, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Alentejo (alentejo, [PT])
Algarve (algarve, [PT])
Azores (azores, [PT])
Beira (beira, [PT])
Fado Houses (fado_houses, [PT])
Madeira (madeira, [PT])
Minho (minho, [PT])
Ribatejo (ribatejo, [PT])
Tras-os-Montes (tras_os_montes, [PT])
Potatoes (potatoes, [AT, DE, AU, CH])
Poutineries (poutineries, [CA, US])
Pub Food (pubfood, [AU])
Rice (riceshop, [JP, TR])
Romanian (romanian, [AT, ES, DE, PL, FR, CH, CZ, BE])
Rotisserie Chicken (rotisserie_chicken, [BR, ES, AR, NL, NZ, MX, PL, AU, CL, FR, IT, PT, BE])
Russian (russian, All)
Salad (salad, All)
Sandwiches (sandwiches, All)
Scandinavian (scandinavian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Schnitzel (schnitzel, [AT, DE, PL, CH])
Scottish (scottish, [AT, GB, IE, DE, CH, CA, US])
Seafood (seafood, All)
Serbo Croatian (serbocroatian, [AT, AR, DE, PL, SE, CL, FR, IT, CH, CZ, BE])
Signature Cuisine (signature_cuisine, [ES, PT, MX, SE, CL, DK, NO, AR])
Singaporean (singaporean, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Slovakian (slovakian, [GB, IE, PL, AU, BE, FR, IT, CZ, CA, US])
Somali (somali, [AT, IT, DE, CH, PL, US])
Soul Food (soulfood, [GB, IE, ES, NL, PL, SE, NO, CA, US])
Soup (soup, All)
Southern (southern, [GB, IE, NL, NZ, PL, SE, TR, CA, US])
Spanish (spanish, All)
Arroceria / Paella (arroceria_paella, [ES])
Sri Lankan (srilankan, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Steakhouses (steak, All)
Supper Clubs (supperclubs, [GB, CA, ES, US])
Sushi Bars (sushi, All)
Swabian (swabian, [AT, DE, CH])
Swedish (swedish, [SE])
Swiss Food (swissfood, [CL, ES, DE, CH, CZ, MX, AR])
Syrian (syrian, All)
Tabernas (tabernas, [ES, TR, PT])
Taiwanese (taiwanese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Tapas Bars (tapas, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Tapas/Small Plates (tapasmallplates, All)
Tavola Calda (tavolacalda, [IT])
Tex-Mex (tex-mex, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Thai (thai, All)
Traditional Norwegian (norwegian, [FR, NO])
Traditional Swedish (traditional_swedish, [FI, SE])
Trattorie (trattorie, [CL, IT, FR, CH, PL, AR])
Turkish (turkish, All)
Chee Kufta (cheekufta, [DE, TR])
Gozleme (gozleme, [TR])
Homemade Food (homemadefood, [TR])
Lahmacun (lahmacun, [TR])
Ottoman Cuisine (ottomancuisine, [TR])
Turkish Ravioli (turkishravioli, [TR])
Ukrainian (ukrainian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Uzbek (uzbek, [US, CZ])
Vegan (vegan, All)
Vegetarian (vegetarian, All)
Venison (venison, [GB, IE, NZ, PL, AU, IT, DK, NO, CZ, SG, CA])
Vietnamese (vietnamese, All)
Waffles (waffles, All)
Wok (wok, [AT, BE, CH, CL, CZ, DE, DK, ES, FI, FR, MX, MY, NL, NO, PH, PT, SE])
Wraps (wraps, [NO, TR, PT, DK, US, SE, CZ])
Yugoslav (yugoslav, [IT, FR, PT, BE, AU, SE])""",

"Shopping" : """Adult (adult, All)
Antiques (antiques, All)
Art Galleries (galleries, All)
Arts & Crafts (artsandcrafts, All)
Art Supplies (artsupplies, All)
Ateliers (ateliers, [AT, DE, NL, TR, IT, CH, DK, NO, BE, JP])
Cards & Stationery (stationery, All)
Cooking Classes (cookingclasses, All)
Costumes (costumes, All)
Embroidery & Crochet (embroideryandcrochet, All)
Fabric Stores (fabricstores, All)
Framing (framing, All)
Paint-Your-Own Pottery (paintyourownpottery, [TW, DE, HK, MY, SG, PH, CA, US])
Auction Houses (auctionhouses, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, NL, NO, NZ, PL, PT, SE, SG, US])
Baby Gear & Furniture (baby_gear, All)
Battery Stores (batterystores, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bespoke Clothing (bespoke, [AT, AU, BE, CA, CH, CZ, DE, DK, ES, FR, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SG, TW, US])
Books, Mags, Music & Video (media, All)
Bookstores (bookstores, All)
Comic Books (comicbooks, All)
Music & DVDs (musicvideo, All)
Newspapers & Magazines (mags, All)
Video Game Stores (videogamestores, All)
Videos & Video Game Rental (videoandgames, All)
Vinyl Records (vinyl_records, All)
Brewing Supplies (brewingsupplies, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bridal (bridal, All)
Cannabis Dispensaries (cannabisdispensaries, [CA, US])
Chinese Bazaar (chinesebazaar, [ES, PT])
Computers (computers, All)
Concept Shops (concept_shops, [AT, AU, BE, CH, CZ, DE, DK, FI, FR, GB, IE, MX, MY, NL, NO, PH, PT, TW])
Cosmetics & Beauty Supply (cosmetics, All)
Customized Merchandise (custommerchandise, All)
Department Stores (deptstores, All)
Diamond Buyers (diamondbuyers, All)
Discount Store (discountstore, All)
Drones (drones, All)
Drugstores (drugstores, [AT, AU, BE, BR, CA, CH, CZ, DE, ES, FI, GB, HK, IE, IT, JP, MY, NL, NZ, PH, PL, PT, SG, TW, US])
Duty-Free Shops (dutyfreeshops, All)
Electronics (electronics, All)
Eyewear & Opticians (opticians, All)
Sunglasses (sunglasses, All)
Farming Equipment (farmingequipment, All)
Fashion (fashion, All)
Accessories (accessories, All)
Ceremonial Clothing (ceremonialclothing, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Children's Clothing (childcloth, All)
Clothing Rental (clothingrental, All)
Department Stores (deptstores, All)
Formal Wear (formalwear, [AR, AT, AU, BE, BR, CA, CL, CZ, DE, DK, ES, FR, GB, IE, MX, NL, NO, NZ, PL, PT, SG, US])
Fur Clothing (furclothing, All)
Hats (hats, [AR, AU, BE, BR, CA, CL, CZ, DE, DK, ES, FI, FR, IT, MX, MY, NL, NO, NZ, PH, PT, SG, TW, US])
Kimonos (kimonos, [JP])
Leather Goods (leather, All)
Lingerie (lingerie, All)
Maternity Wear (maternity, All)
Men's Clothing (menscloth, All)
Plus Size Fashion (plus_size_fashion, [AT, AU, BE, BR, CH, CZ, DE, DK, ES, FI, FR, IT, MY, NL, NO, NZ, PH, PT, SE, TW, US])
Shoe Stores (shoes, All)
Sleepwear (sleepwear, [AU, PT])
Sports Wear (sportswear, All)
Dance Wear (dancewear, All)
Stockings (stockings, [AT, DE, CH, PT, NL, BE, CZ])
Surf Shop (surfshop, [AR, AT, AU, CH, CL, DE, DK, ES, GB, HK, IT, JP, MX, MY, NZ, PH, PL, PT, TR, TW, US])
Swimwear (swimwear, All)
Traditional Clothing (tradclothing, All)
Used, Vintage & Consignment (vintage, All)
Women's Clothing (womenscloth, All)
Fireworks (fireworks, [GB, AR, PT, NZ, MX, AU, CL, CZ, CA, US])
Fitness/Exercise Equipment (fitnessequipment, All)
Flea Markets (fleamarkets, All)
Flowers & Gifts (flowers, All)
Cards & Stationery (stationery, All)
Florists (florists, All)
Gift Shops (giftshops, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SE, TW, US])
Gemstones & Minerals (gemstonesandminerals, All)
Gold Buyers (goldbuyers, [AT, BR, ES, DE, NL, SE, BE, FR, IT, CH, PT, CA, US])
Guns & Ammo (guns_and_ammo, [AT, ES, AR, DE, PT, MX, MY, PL, CL, CH, PH, CA, US])
Head Shops (headshops, All)
High Fidelity Audio Equipment (hifi, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Hobby Shops (hobbyshops, All)
Home & Garden (homeandgarden, All)
Appliances (appliances, All)
Candle Stores (candlestores, All)
Christmas Trees (christmastrees, All)
Furniture Stores (furniture, All)
Grilling Equipment (grillingequipment, All)
Hardware Stores (hardware, All)
Holiday Decorations (holidaydecorations, All)
Home Decor (homedecor, All)
Hot Tub & Pool (hottubandpool, All)
Kitchen & Bath (kitchenandbath, All)
Kitchen Supplies (kitchensupplies, All)
Lighting Stores (lightingstores, All)
Linens (linens, [AT, DE, PT, FR, IT, CH, DK, CZ, NO, BE])
Materiale elettrico (materialeelettrico, [CL, IT, ES, MX, AR])
Mattresses (mattresses, All)
Nurseries & Gardening (gardening, All)
Hydroponics (hydroponics, All)
Outdoor Furniture Stores (outdoorfurniture, All)
Paint Stores (paintstores, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, IE, IT, JP, MX, NL, NO, NZ, PL, SE, SG, US])
Playsets (playsets, All)
Pumpkin Patches (pumpkinpatches, [US])
Rugs (rugs, [AR, AU, BE, BR, CA, CL, DK, ES, FI, FR, GB, IT, MX, MY, NL, NO, NZ, PH, PT, SE, SG, TR, TW, US])
Sheds & Outdoor Storage (shedsandoutdoorstorage, [AR, AT, AU, BE, BR, CA, CH, CL, DE, GB, IE, IT, MX, MY, NL, NZ, PH, PL, PT, SG, US])
Tableware (tableware, [AT, BR, AR, DE, PT, NL, MX, CL, FR, CH, DK, CZ, NO, BE, US])
Horse Equipment Shops (horsequipment, [AR, AT, AU, BE, BR, CA, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, NL, NO, PL, PT, SE, SG, US])
Jewelry (jewelry, All)
Kiosk (kiosk, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, JP, MX, MY, NL, NO, PH, PL, PT, SE, TR, TW])
Knitting Supplies (knittingsupplies, All)
Livestock Feed & Supply (livestocksupply, All)
Luggage (luggage, All)
Market Stalls (marketstalls, [AT, GB, IE, DE, PT, PL, IT, CH, NO, CZ, DK])
Medical Supplies (medicalsupplies, All)
Military Surplus (militarysurplus, All)
Mobile Phone Accessories (cellphoneaccessories, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, NL, NO, NZ, PT, SE, SG, TW, US])
Mobile Phones (mobilephones, All)
Motorcycle Gear (motorcyclinggear, [AR, AT, AU, BE, BR, CH, CL, CZ, DE, DK, ES, FI, FR, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, SE, SG, TR, TW, US])
Musical Instruments & Teachers (musicalinstrumentsandteachers, All)
Office Equipment (officeequipment, All)
Outlet Stores (outlet_stores, All)
Packing Supplies (packingsupplies, [AT, IE, BR, DE, NZ, AU, CZ, SG, DK, PT, FR, JP, BE, US, GB, NL, CH, NO, CA])
Pawn Shops (pawn, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Perfume (perfume, [AR, AT, AU, BE, BR, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PT, SE, TW, US])
Personal Shopping (personal_shopping, [AT, AU, BE, CA, CH, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Photography Stores & Services (photographystores, All)
Pool & Billiards (poolbilliards, [AU, BE, BR, CA, DK, FR, GB, HK, IE, IT, JP, MY, NL, NZ, PH, PT, SG, TR, TW, US])
Pop-up Shops (popupshops, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Props (props, [BE, US])
Public Markets (publicmarkets, All)
Religious Items (religiousitems, All)
Safe Stores (safestores, All)
Safety Equipment (safetyequipment, All)
Scandinavian Design (scandinaviandesign, [FI, DK, SE, NO])
Shopping Centers (shoppingcenters, All)
Shopping Passages (shoppingpassages, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
Souvenir Shops (souvenirs, [AR, AT, AU, BE, BR, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Spiritual Shop (spiritual_shop, All)
Sporting Goods (sportgoods, All)
Bikes (bikes, All)
Dive Shops (diveshops, [AT, BR, ES, DE, NZ, MX, AU, CL, IT, CH, AR, JP, US])
Golf Equipment (golfequipment, [CA, DE, NL, BE, AU, US])
Hockey Equipment (hockeyequipment, All)
Hunting & Fishing Supplies (huntingfishingsupplies, All)
Outdoor Gear (outdoorgear, All)
Skate Shops (skateshops, All)
Ski & Snowboard Shops (skishops, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, ES, FI, FR, GB, IE, IT, JP, NL, NO, NZ, PL, SE, US])
Sports Wear (sportswear, All)
Dance Wear (dancewear, All)
Tabletop Games (tabletopgames, All)
Teacher Supplies (teachersupplies, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Thrift Stores (thrift_stores, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Tickets (tickets, [PT, PL, SE, CZ, FI, CL, NO, DK])
Tobacco Shops (tobaccoshops, All)
Toy Stores (toys, All)
Trophy Shops (trophyshops, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, PH, PL, PT, TW, US])
Uniforms (uniforms, [AR, AU, BE, BR, CA, CL, DE, DK, ES, FI, FR, GB, HK, IT, MX, MY, NO, NZ, PH, PL, PT, SG, TW, US])
Used Bookstore (usedbooks, [AT, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Vape Shops (vapeshops, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Vitamins & Supplements (vitaminssupplements, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TR, TW, US])
Watches (watches, All)
Wholesale Stores (wholesale_stores, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Wigs (wigs, [AR, AU, BE, CA, CL, CZ, DE, DK, ES, FI, FR, IT, MX, NL, NO, PL, PT, US])""",

"Education" : """Education (education, All)
Adult Education (adultedu, All)
Art Classes (artclasses, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Glass Blowing (glassblowing, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
College Counseling (collegecounseling, [US, PT])
Colleges & Universities (collegeuniv, All)
Educational Services (educationservices, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Elementary Schools (elementaryschools, All)
Middle Schools & High Schools (highschools, All)
Montessori Schools (montessori, All)
Preschools (preschools, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Private Schools (privateschools, [BR, ES, PT, NZ, MX, AU, SE, CL, DK, NO, CZ, AR, US])
Private Tutors (privatetutors, All)
Religious Schools (religiousschools, [BR, ES, PT, NZ, MX, MY, AU, CL, DK, NO, CZ, AR, PH, US])
Special Education (specialed, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Specialty Schools (specialtyschools, All)
Art Schools (artschools, All)
Bartending Schools (bartendingschools, All)
CPR Classes (cprclasses, [US, AU, SE, PT])
Cheerleading (cheerleading, [AT, DE, CH, CA, SE, US])
Childbirth Education (childbirthedu, [AT, IE, BR, ES, DE, NZ, AU, SE, SG, DK, PH, FR, BE, US, GB, NL, MY, PL, IT, CH, NO, CA])
Circus Schools (circusschools, [BR, ES, MX, FI, CL, FR, PT, AR])
Cooking Schools (cookingschools, All)
Cosmetology Schools (cosmetology_schools, All)
DUI Schools (duischools, [US])
Dance Schools (dance_schools, All)
Drama Schools (dramaschools, All)
Driving Schools (driving_schools, All)
Firearm Training (firearmtraining, [US])
First Aid Classes (firstaidclasses, [AR, AT, AU, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IT, JP, MX, MY, NO, PH, PL, PT, SE, TR, TW, US])
Flight Instruction (flightinstruction, All)
Food Safety Training (foodsafety, [BR, US, SG, PT])
Language Schools (language_schools, All)
Massage Schools (massage_schools, All)
Nursing Schools (nursingschools, All)
Parenting Classes (parentingclasses, All)
Photography Classes (photoclasses, All)
Pole Dancing Classes (poledancingclasses, [AU, BR, CZ, DE, DK, FI, FR, HK, IT, JP, MY, NL, NO, NZ, PH, SE, SG, TW, US])
Samba Schools (sambaschools, [FI, BR, SE, IT])
Ski Schools (skischools, All)
Speech Training (speechtraining, All)
Surf Schools (surfschools, All)
Swimming Lessons/Schools (swimminglessons, All)
Traffic Schools (trafficschools, [US])
Vocational & Technical School (vocation, All)
Tasting Classes (tastingclasses, All)
Cheese Tasting Classes (cheesetastingclasses, All)
Wine Tasting Classes (winetasteclasses, All)
Test Preparation (testprep, All)
Tutoring Centers (tutoring, All)
Waldorf Schools (waldorfschools, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])""",

"Financial Services" : """"Financial Services (financialservices, All)
Banks & Credit Unions (banks, All)
Business Financing (businessfinancing, All)
Check Cashing/Pay-day Loans (paydayloans, [AR, AU, BE, BR, CA, CL, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, PH, PL, PT, SE, SG, TR, TW, US])
Currency Exchange (currencyexchange, All)
Debt Relief Services (debtrelief, [CA, US])
Financial Advising (financialadvising, All)
Installment Loans (installmentloans, [US])
Insurance (insurance, All)
Auto Insurance (autoinsurance, [AR, AU, BE, BR, CL, CZ, DK, ES, IT, JP, MX, NL, NO, PL, PT, SE, TR, US])
Home & Rental Insurance (homeinsurance, All)
Life Insurance (lifeinsurance, [AR, AU, BE, BR, CL, CZ, DK, ES, GB, IE, IT, JP, MX, NL, NO, NZ, PL, SE, SG, TR, US])
Investing (investing, All)
Mortgage Lenders (mortgagelenders, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Tax Services (taxservices, All)
Title Loans (titleloans, [CA, US])""",

"Mass Media" : """Print Media (printmedia, All)
Radio Stations (radiostations, All)
Television Stations (televisionstations, All)"""

}

def main():

# Store API Key in an environment variable for security
    API_KEY = 'L29E0LQam3wU-MyuHinbiJ7y950Cbb7LX5HoAbM2lb47ZAbLTnP0HS6IM_idE9JNHGbLn1x_9JoFvK8B7i4TuS90ZSA0U8YQP9lA0JD82jA9y6BsJCkltciUh_BZZ3Yx'  # Use your actual API key

# Base URL for Yelp API
    url = 'https://api.yelp.com/v3/businesses/search'

    # Headers for the API request (including the API Key in the Authorization header)
    headers = {
        'Authorization': f'Bearer {API_KEY}',  # Pass the API Key as a Bearer Token
    }

    # Search parameters for businesses in Oregon (or a specific city like Portland)
    params = {
        'location': 'Montana',    # Location to search (replace with a city, like 'Portland, OR')
        'limit': 20,             # Limit to 10 results (you can increase this or paginate)
        # 'sort_by': 'rating',     # Sort by rating
    }

    # Send the GET request to Yelp API
    response = requests.get(url, headers=headers, params=params)

    # Check if the request was successful
    if response.status_code == 200:
        businesses = response.json().get('businesses', [])
        if businesses:
            for business in businesses:
                # Extract the relevant information
                business_id = business['id']
                name = business['name']
                city = business['location'].get('city', '')
                state = business['location'].get('state', '')
                # Handle address properly (join address components)
                address_parts = [
                    business['location'].get('address1', ''),
                    business['location'].get('address2', ''),
                    business['location'].get('address3', '')
                ]
                # Join only non-empty address parts
                address = ' '.join(part for part in address_parts if part)

                latitude = business['coordinates'].get('latitude', '')
                longitude = business['coordinates'].get('longitude', '')
                rating = business['rating']
                categories = ', '.join([category['title'] for category in business['categories']])

                # Print the extracted data
                print(f"Business ID: {business_id}")
                print(f"Name: {name}")
                print(f"City: {city}")
                print(f"State: {state}")
                print(f"Address: {address}")
                print(f"Latitude: {latitude}")
                print(f"Longitude: {longitude}")
                print(f"Rating: {rating}")
                print(f"Categories: {categories}")
                print('-' * 40)

                print(f"{business_id},{name},{city},{state},{address},{latitude},{longitude},{rating},{categories}")
        else:
            print("No businesses found for the given query.")
    else:
        print(f"Error: {response.status_code}, {response.text}")


    # with open('take2_2.csv', 'r') as infile, open('take2_3.csv', 'w', newline='') as outfile:
        
    #     reader = csv.reader(infile)
    # #     # data = json.load(infile)
    # #     fieldnames = ['Business ID', 'Name', 'City', 'State', 'Address', 'Latitude', 'Longitude', 'Stars', 'Categories', 'Subcategories']
    #     writer = csv.writer(outfile)
        
        # Test 
        # for row in reader:
        #     if row[0] != 'Business ID':
        #         categories = row[8]
        #         subcategories_list = [category.strip() for category in row[9].split(',')]

        # for row in reader:
        #     refined_subcat_list = []
        #     if row[0] != 'Business ID':
        #         categories = row[8]
        #         subcategories_list = [category.strip() for category in row[9].split(',')]
        #         for i in range(len(subcategories_list)):
        #             if subcategories_list[i] not in categories:
        #                 refined_subcat_list.append(subcategories_list[i])
                
        #         # print(refined_subcat_list)
        #         str = ''
        #         for i in range(len(refined_subcat_list)):
        #             if i != len(refined_subcat_list) - 1:
        #                 str += f"{refined_subcat_list[i]}, "
        #             else:
        #                 str += f"{refined_subcat_list[i]}"
                
        #         # print(str)

            
        #         writer.writerow([row[0], row[1], row[2], row[5], row[6], row[7], row[8], str])



        # for row in reader:
        #     categories_list = [category.strip() for category in row[8].split(',')]
        #     category_set = set()
        #     for category in categories_list:
        #         for key, value in better_categories_list.items():
        #             if category in value and category != key:
        #                 category_set.add(key)
            
        #     cat_list = list(category_set)
        #     str = ""
        #     for i in range(len(cat_list)):
        #         if i != len(cat_list) - 1:
        #             str += f"{cat_list[i]}, "
        #         else:
        #             str += f"{cat_list[i]}"

        #     writer.writerow([row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], str, row[8]])

        # for line in infile:
        #     data = json.loads(line)
        #     # if data['is_open'] == 1:
        #     business_id = data['business_id']
        #     name = data['name']
        #     city = data['city']
        #     state = data['state']
        #     address = data['address']
        #     latitude = data['latitude']
        #     longitude = data['longitude']
        #     stars = data['stars']
        #     categories = data['categories']

        #     writer.writerow([business_id, name, city, state, address, latitude, longitude, stars, categories])


if __name__ == '__main__':
    main()